leadlogistics/leadlogistics/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.MainView.as_view(),name = 'index'),
    path('fleet/',views.FleetView.as_view(),name = 'fleet'),
    #path('contact/',views.ContactView.as_view(),name = 'contact'),
    path('sample/',views.SampleView.as_view(),name = 'sample'),
    path('services/',views.ServiceView.as_view(),name = 'services'),
    path('Thanks/',views.Thanks.as_view(),name = 'Thanks'),
    path('leadlogisticsApp/',include('leadlogisticsApp.urls',namespace = 'leadlogisticsApp')),

]

leadlogistics/leadlogisticsApp/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from django.contrib.auth import REDIRECT_FIELD_NAME
from . import views

app_name = 'leadlogisticsApp'

urlpatterns = [
    #path('login/',auth_views.LoginView.as_view(),name = 'login'),
    #re_path(r'^detail/(?P<pk>\d+)/$', views.DocketDetail.as_view(), name= 'detail'),
    #path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name = 'login'),
    #path('docketstatus/',views.DocketCreate.as_view(), name = 'docketstatus'),
    path('nodata/',views.nodata, name = 'nodata'),
    path('list/',views.DocketList, name = 'list'),
    path('detail/',views.DetailList, name = 'detail'),
    path('ContactUs/',views.ContactUs, name = 'ContactUs'),

    #path('detail/<int:pk>/', views.DocketDetail.as_view(), name= 'detail'),
    #re_path(r'^detail/(?P<pk>\d+)/$', views.DocketDetail.as_view(), name= 'detail'),
    #path('detail/(?P<slug>[-\w]+)/',views.DocketDetail.as_view(), name = 'detail'),
    #path('detail/',views.DocketDetail.as_view(), name = 'detail'),
    #re_path(r'^(?P<pk>\d+)/$', views.DocketDetail.as_view(), name= 'detail'),

    #path('signup/',views.SignUp.as_view(),name = 'signup')

]

leadlogistics/leadlogisticsApp/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils.text import slugify
from django import template
from django.contrib.auth.models import User
register = template.Library()
from django.urls import reverse


DOCKET_CHOICES = (
    ("Shipment Pickup From Origin", "Shipment Pickup From Origin"),
    ("Received At Origin Warehouse", "Received At Origin Warehouse"),
    ("In Transit", "In Transit"),
    ("Received At Destination WareHouse", "Received At Destination WareHouse"),
    ("Out For Delivery", "Out For Delivery"),
    ("Delivered", "Delivered"),
)

alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')

# Create your models here.

class Docket(models.Model):
    DocketId = models.CharField(max_length=50, unique=True, validators=[alphanumeric])
    DocketStatus  = models.CharField(max_length=128,choices = DOCKET_CHOICES)
    EntryText = models.CharField(max_length=128,blank=True,default='')

    #slug = models.SlugField(allow_unicode=True,unique=True)
    #DocketStatus  = models.CharField(max_length=128)
    #slug = models.SlugField(allow_unicode=True,unique=True)

    def __str__(self):
        return self.DocketId
    # def save(self,*args,**kwargs):
    #     self.slug = slugify(self.DocketId)
    #     super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse("leadlogisticsApp:nodata")

    class Meta:
        unique_together = ('DocketId','DocketStatus')

        #self.slug = slugify(self.name)
        #print("pk is : ",self.pk)
        #return reverse("leadlogisticsApp:detail",kwargs={'pk':self.kwargs.get("id")})


class Contact(models.Model):
    name = models.CharField(max_length=128,blank=False)
    email = models.EmailField(blank=False)
    phone = models.PositiveIntegerField(blank=False)
    subject = models.CharField(max_length=256,blank=False)
    requirements = models.TextField()


    def __str__(self):
        return self.name

leadlogistics/leadlogisticsApp/forms.py
from django import forms
from django.contrib.auth.models import User
from leadlogisticsApp.models import Docket,Contact
from django.contrib import admin

class DocketForm(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = Docket
        fields = ('DocketId',)

    def clean_asset_code(self):
            DocketId = self.cleaned_data['DocketId']
            if Docket.objects.filter(DocketId=DocketId).exists():
                raise forms.ValidationError("This Docket entry already exist.")
            return DocketId

class DocketAdmin(admin.ModelAdmin):
    form = DocketForm



class ContactUsForm(forms.ModelForm):
    class Meta():
        model = Contact
        fields = '__all__'

leadlogistics/leadlogistics/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

# Create your views here.

class MainView(TemplateView):
    template_name = 'index.html'

class FleetView(TemplateView):
    template_name = 'fleet.html'

class ContactView(TemplateView):
    template_name = 'contact.html'

class SampleView(TemplateView):
    template_name = 'sample.html'

class ServiceView(TemplateView):
    template_name = 'services.html'

class Thanks(TemplateView):
    template_name = 'Thanks.html'

def nodata(request):
    return render(request,'nodata.html')

leadlogistics/leadlogisticsApp/views.py
from django.shortcuts import render,redirect
#from django.views.generic.base import TemplateView
from django.views.generic import TemplateView
from django.views.generic import CreateView,ListView,DetailView
from leadlogisticsApp import models
from leadlogisticsApp.forms import ContactUsForm
from django.urls import reverse,reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
import smtplib

# Create your views here.

def nodata(request):
    return render(request,'leadlogisticsApp/Docket_nodata.html')

def DocketList(request):
    #obj = models.Docket.objects.all()
    return render(request,'leadlogisticsApp/Docket_form.html')

def DetailList(request):
    obj = models.Docket.objects.all()
    #data =
    #print(request.GET.get('Docket'))
    data = request.GET.get('Docket')
    #print("length is: ",len(obj))
    k = len(obj)

    for content in obj:

        #print(str(content))
        if data == str(content):
            #print("data Found")
            pass

        else:
            k -= 1
            if k == 0:
                #print(" No data Found")
                return HttpResponseRedirect(reverse('leadlogisticsApp:nodata'))


    return render(request,"leadlogisticsApp/Docket_detail.html",{'obj':obj,'data':data})


def ContactUs(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            Name = form['name'].value()
            Email = form['email'].value()
            Phone = form['phone'].value()
            Subject = form['subject'].value()
            Requirements = form['requirements'].value()
            s = smtplib.SMTP('smtp.gmail.com', 587)
            s.starttls()
            s.login("raki.039@gmail.com", "Hamsa@123")
            msg = ("From: %s\r\nTo: %s\r\n\r\nPhone: %s\r\n Subject: %s\r\n Requirements: %s\r\n"
       % (Email,Email,Phone,Subject,Requirements))

            s.sendmail("raki.039@gmail.com", "raki.039@gmail.com", msg)
            s.quit()
            return HttpResponseRedirect(reverse('Thanks'))

    else:
        form = ContactUsForm()

    return render(request,'leadlogisticsApp/contact.html',{'form': form})

leadlogistics/leadlogisticsApp/templates/leadlogisticsApp/Docket_detail.html
{% extends "base.html" %}

{% block content %}
 <!-- This basically creates the 12 grid layout -->
 <style>
   .data {
     width: 100%;
     padding: 12px 20px;
     margin: 8px 0;
     text-align: center;

     border-radius: 4px;

   }


	 .sample {
	width: 100px;
	height: 100px;
	background-color: red;
	position: relative;
	animation-name: example;
	animation-duration: 4s;
	border-radius: 25px;
	opacity: 50%;





}

p {

 text-align: center;
 word-spacing: 175px;
 position: fixed;
}

.alert{
	text-align:justify;
  text-justify:auto;
}



@keyframes example {
	0%   {background-color:red; left:0px; top:0px;object-position: 0% 0%;}
	16.6%  {background-color:red; left:200px; top:0px;object-position: 0% 0%;}
	33.26%  {background-color:red; left:400px; top:0px;object-position: 0% 0%;}
	49.86%  {background-color:red; left:600px; top:0px;}
	66.46%  {background-color:red; left:800px; top:0px;}
	83.06%  {background-color:red; left:1000px; top:0px;}
	100%  {background-color:red; left:1200px; top:0px;}



}

 </style>

	<div class="container">
    <br>


			{% for i in obj %}


				{% if i.DocketId == data %}
				<div class="alert alert-primary data" role="alert">
					<h1>DocketId: {{i.DocketId}}</h1>
					<h1>Docket Status:{{ i.DocketStatus }}</h1>
					<h1>Docket Text:{{ i.EntryText }}</h1>

				</div>

				{% endif %}





			{% endfor %}

    </div>


<br>
<br>
<br>
<br>
<br>
<ul>

<h4>Docket States:</h4>

<li>Shipment_Pickup_From_Origin</li>
<li>Received_At_Origin_Warehouse</li>
<li>In_Transit</li>
<li>Received_At_Destination_WareHouse</li>
<li>Out_For_Delivery</li>
<li>Delivered</li>

</ul>





{% endblock %}

leadlogistics/leadlogisticsApp/templates/leadlogisticsApp/Docket_form.html
{% extends "base.html" %}



{% block content %}
<style>

.text {
  width: 50%;
  padding: 12px 20px;
  margin: 8px 0;
  border: 1px solid #ccc;
  border-radius: 4px;
  

}
</style>
<div class="container">
  <br>
  <h4>Enter Tracking/Docket No of the Shipment</h4>
  <form method="GET" action="{% url 'leadlogisticsApp:detail' %}">
  	{% csrf_token %}
    <input type="text" name="Docket" value="" required class="text">
    <br>
    <p></p>
    <input type="Submit" class="btn btn-warning" value="Submit">

  </form>
</div>
{% endblock %}

leadlogistics/leadlogisticsApp/templates/leadlogisticsApp/Docket_list.html
{% extends "base.html" %}

{% block content %}
 <!-- This basically creates the 12 grid layout -->

	<div class="content">

	
    <br>
    {% for docket in object_list %}
			<h3 class="mb-1">Docket Id:{{ docket.DocketId }}</h3>
			<h5 class="mb-1">Status: {{ docket.DocketStatus}}</h5>
      <br>
    {% endfor %}

    </div>

{% endblock %}

<!-- {% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		<a href="{% url 'groups:single' slug=group.slug %}"
		class="list-group-item list-group-item-action flex-column align-items-start">
			<h3 class="mb-1">{{ group.name }}</h3>
			<p class="mb-1">{{ group.description_html|safe }}</p>
			<div class="d-flex w-40 justify-content-between">
				<small class="text-muted"><span class="badge badge-secondary">
					{{ group.members.count }}</span> member{{ group.members.count|pluralize }}</small>
				<small class="text-muted"><span class="badge badge-secondary">
					{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}</small>
			<span></span><span></span>
			</div>
		</a>

		{% endfor %}
	</div>
</div>
{% endblock %} -->

leadlogistics/leadlogisticsApp/templates/leadlogisticsApp/Docket_nodata.html
{% extends "base.html" %}

{% block content %}

<style>
  .nodata {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    text-align: center;

    border-radius: 4px;

  }

</style>
<div class="container">


<br>
<div class="alert alert-danger nodata"  role="alert">
<h1>No Data Found for this docket</h1>
</div>
</div>

<!-- <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><h1>No Data Found for this docket</h1></strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div> -->

{% endblock %}

leadlogistics/leadlogisticsApp/templates/leadlogisticsApp/animation.html
<!DOCTYPE html>
<html>
<head>
	<title>CSS Animations</title>
	<style type="text/css">

body {
	background: #303030;
	font: 1.1em sans-serif;
}
.wrap {
	box-sizing: border-box;
	margin: 70px auto;
	padding: 5px;
	width: 600px;
	border-radius: 10px;
	background: #222;
	box-shadow: inset 0 0 1px rgba(0,0,0,.6), 0 1px 0 rgba(255,255,255,.1);
}
.prog-bar {
	height: 60px;
	border-radius: 5px;
	background: -webkit-repeating-linear-gradient(-45deg, rgba(255,255,255,.1), rgba(255,255,255,0) 12px), -webkit-linear-gradient(#F5A8A8, #F08080);

	-webkit-animation-name: slide;
	-moz-animation-name: slide;
	-o-animation-name: slide;
	animation-name: slide;

	-webkit-animation-duration: 2s;
	-moz-animation-duration: 2s;
	-o-animation-duration: 2s;
	animation-duration: 2s;

	-webkit-animation-timing-function: linear;
	-moz-animation-timing-function: linear;
	-o-animation-timing-function: linear;
	animation-timing-function: linear;
}

/*	Keyframes
------------------------------------------ */

@-webkit-keyframes slide {
	0%   { width:   0%; }
	30%,
	60%  { width:  50%; }
	70%  { width:  80%; }
	100% { width: 100%; }
}
@-moz-keyframes slide {
	0%   { width:   0%; }
	30%,
	60%  { width:  50%; }
	70%  { width:  80%; }
	100% { width: 100%; }
}
@-o-keyframes slide {
	0%   { width:   0%; }
	30%,
	60%  { width:  50%; }
	70%  { width:  80%; }
	100% { width: 100%; }
}
@keyframes slide {
/*
	can simply define start and end, or with percentage in progress
	from { width:   0%; }
	to   { width: 100%; }
*/
	0%   { width:   0%; }
	30%,
	60%  { width:  50%; }
	70%  { width:  80%; }
	100% { width: 100%; }
}
	</style>
</head>
<body>
	<div class="wrap">
		<div class="prog-bar"></div>
	</div>
</body>
</html>

leadlogistics/leadlogisticsApp/templates/leadlogisticsApp/contact.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}

<style >


.background {
  color: white;
}

h3{
    color: white;
     text-indent: 50px;
     letter-spacing: 3px;
     word-spacing: 10px;
     text-align: center;
}

</style>

  <p></p>
  <h3>How To Reach Us?</h3>
  <div class="container background">
    <br>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {% bootstrap_form form %}

      <input type="submit" name="" value="Submit Message">
      </div>
      


  </div>


 </div>
 {% endblock %}

leadlogistics/templates/Thanks.html
{% extends 'base.html' %}
{% block content %}

<style >


.container {
  color: white;
   text-indent: 50px;
   letter-spacing: 3px;


   word-spacing: 10px;

}

h1{

    color: white;
     text-indent: 50px;
     letter-spacing: 3px;


     word-spacing: 10px;


}

</style>

  <p></p>
  <h3>Thank You,we will contact you soon</h3>



 </div>
 {% endblock %}

leadlogistics/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Lead Logistics</title>
    <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<style>
.cls-image {
  width:400px;
  height:140px;

}

.btn-outline-primary
{
#background-image: None;
background-color: None;
background-outline: None;
outline-style:none;
}


.main {
  background-color: #007bff;
}

#rcorners1 {
  opacity: 1;

  border-style: none;
  color: #007bff;
  padding: 30px 30px;
  text-align: center;
  font-size: 30px;

}

#rcorners1:hover {
opacity: 1;
background-color: #007bff;

  border-radius: 10px;
  color: white;
  padding: 30px 30px;
  text-align: center;
  font-size: 30px;
  transition: 0;

  }


</style>
<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'leadlogisticsApp/css/sample.css' %}">

    <!-- <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}"> -->
  </head>
  <body class="main">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >  <!-- style="background-color: red;" -->
  <!-- <a class="navbar-brand" href="{% url 'index' %}"> <img src={% static "LeadLogistics-3.png" %} alt=""></im> LeadLogistics</a> -->
  <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'leadlogisticsApp/LeadLogistics-3.png' %}" class="cls-image"> </a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item active">
        <a class="navbar-brand" id="rcorners1" href="{% url 'index' %}">HOME</button><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="navbar-brand" id="rcorners1" href="{% url 'services' %}">SERVICES</button></a>
      </li>

      <li class="nav-item">

      </li>
      <li class="nav-item">
        <a class="navbar-brand" id="rcorners1" href="{% url 'leadlogisticsApp:list' %}">TRACKING/DOCKET STATUS</a>
      </li>
      <!-- <li class="nav-item">
        <a class="navbar-brand" id="rcorners1" href="">PAY OPTIONS</a>

      </li>
      <li class="nav-item">
        <a class="navbar-brand " href="{% url 'fleet' %}" id="rcorners1"  >FLEET</button></a>
      </li> -->

      <a class="navbar-brand" id="rcorners1" href="{% url 'leadlogisticsApp:ContactUs' %}">CONTACT US</a>

      </div>
    </ul>

  </div>
</nav>

<div class="mycontent">

{% block content %}

{% endblock %}
</div>

<!-- Footer -->
<footer class="page-footer font-small blue pt-4">
  <!-- Footer Links -->
<div class="navbar_bottom">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- <a class="navbar-brand" href="{% url 'index' %}">Partners</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Customers <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sample' %}">Pay Terms</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">VAS</a>
        </li>
      </ul>

      <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://google.com/"> google.com</a>
      </div>
    </div> -->
  </nav>
  </div>
</footer>
<!-- Footer -->

  </body>

</html>

leadlogistics/templates/index.html
{% extends 'base.html' %}


{% block content %}
<style>

p {
  color: white;
   text-indent: 50px;
   letter-spacing: 3px;
   font-size: 20px;
   word-spacing: 10px;

}

h1 {
  color: white;
}


</style>

<div class="form-group">
   <label for="exampleFormControlTextarea1"></label>
   <!-- <p>Welcome to the Lead Logistics, Bangalore (India) - Your destination to a complete supply chain network. We bring you a one-stop solution for all your logistic requirements - Sharing with you thousands of solutions that we have customized for our discerning customers, across the country and catering to multiple domains across various industry verticals.</p> -->
   <!-- <textarea class="form-control" id="exampleFormControlTextarea1" rows="10"></textarea> -->
   <div id="back">

     <h1>Welcome to Lead Logistics</h1>
<p>Your destination to a complete supply chain network. We bring you a one-stop solution for all your logistic requirements - Sharing with you thousands of solutions that we have customized for our discerning customers, across the country and catering to multiple domains across various industry verticals.

We are a team with clear objectives to ensure customer-centric and customized logistics solutions are served with precision. We have re-engineered processes to achieve better result and meet, and often exceed comprehensive global logistics standards.
</div>



<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://source.unsplash.com/400x400/?Shipment,courier,Trasportation" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://source.unsplash.com/400x400/?coldstorage,Courier,trasportation" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://source.unsplash.com/400x400/?Warehousing,Courier,Trasportation" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

 </p>
 </div>
 {% endblock %}

leadlogistics/templates/nodata.html
{% extends "base.html" %}

{% block content %}

<h1>No Data Found</h1>

{% endblock %}

leadlogistics/templates/sample.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img {% static "leadlogisticsApp/prima.jpg" %} class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img {% static "leadlogisticsApp/prima.jpg" %} class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img {% static "leadlogisticsApp/prima.jpg" %} class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% endblock %}

leadlogistics/templates/services.html
{% extends 'base.html' %}
{% block content %}
<style>


.container {
  color: white;
   text-indent: 50px;
   letter-spacing: 3px;
   word-spacing: 10px;
}

h1 {
  color: white;
}

</style>

<div class=" container form-group">
  <br>
  <h1>Our Servies</h1>
  <ol>
    <ul>
      <li>rakesh</li>
    </ul>
    <li> FTL- Full Truck Load</li>
    <li>LCL Consolidation</li>
    <li>Project Handling</li>
  </ol>
  </div>


  <div class="container form-group">
    <h1>Our Upcoming Servies</h1>
    <ol>
      <li>Warehousing.</li>
      <li>Warehousing & Distribution</li>
      <li>Cold Storage & Distrubtion</li>
      <li>PAN India LCL & FTL Service</li>
    </ol>
    </div>

 </div>
 {% endblock %}